run-dist:
	./build/install/app/bin/app

run:
	gradle run

test:
	gradle test

report:
	./gradlew jacocoTestReport

lint:
	gradle checkstyleMain

build:
	gradle clean
	gradle installDist

.PHONY: build

